-- Flutter + Supabase Tasks Demo
-- Ejecuta este archivo en Supabase Dashboard > SQL Editor.
-- Incluye tabla, permisos, RLS policies y activación de Realtime.

begin;

create table if not exists public.tasks (
  id bigint generated by default as identity primary key,
  user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  title text not null check (char_length(title) between 1 and 120),
  is_done boolean not null default false,
  created_at timestamptz not null default now()
);

comment on table public.tasks is 'Tareas por usuario para demo Flutter + Supabase';
comment on column public.tasks.user_id is 'Usuario dueño de la tarea. Se llena con auth.uid()';

alter table public.tasks enable row level security;

grant usage on schema public to authenticated;
grant select, insert, update, delete on public.tasks to authenticated;
grant usage on all sequences in schema public to authenticated;

drop policy if exists "tasks_select_own" on public.tasks;
drop policy if exists "tasks_insert_own" on public.tasks;
drop policy if exists "tasks_update_own" on public.tasks;
drop policy if exists "tasks_delete_own" on public.tasks;

create policy "tasks_select_own"
on public.tasks
for select
to authenticated
using ((select auth.uid()) = user_id);

create policy "tasks_insert_own"
on public.tasks
for insert
to authenticated
with check ((select auth.uid()) = user_id);

create policy "tasks_update_own"
on public.tasks
for update
to authenticated
using ((select auth.uid()) = user_id)
with check ((select auth.uid()) = user_id);

create policy "tasks_delete_own"
on public.tasks
for delete
to authenticated
using ((select auth.uid()) = user_id);

-- Realtime necesita replica identity para updates/deletes completos.
alter table public.tasks replica identity full;

-- Agrega la tabla a la publicación de Realtime.
-- Si ya fue agregada desde el dashboard, se ignora el error.
do $$
begin
  alter publication supabase_realtime add table public.tasks;
exception
  when duplicate_object then null;
end $$;

commit;
