-- Flutter + Supabase Tasks Demo
-- Charla 2: soporte de Functions y procesos automaticos.
--
-- Ejecuta este archivo en Supabase Dashboard > SQL Editor despues de
-- `supabase/01_schema_tasks.sql`.
-- Crea una tabla visible para revisar las ejecuciones y una funcion SQL que
-- puede ser llamada por una Edge Function o por un job programado.

begin;

create table if not exists public.task_automation_runs (
  id bigint generated by default as identity primary key,
  run_type text not null default 'manual'
    check (run_type in ('manual', 'cron', 'trigger', 'test')),
  source text not null default 'edge-function',
  total_tasks bigint not null default 0,
  pending_tasks bigint not null default 0,
  completed_tasks bigint not null default 0,
  notes text,
  created_at timestamptz not null default now()
);

comment on table public.task_automation_runs is
  'Registro de procesos automaticos para la charla 2 de Supabase Edge Functions';
comment on column public.task_automation_runs.run_type is
  'Origen logico de la ejecucion: manual, cron, trigger o test';
comment on column public.task_automation_runs.source is
  'Componente que pidio la ejecucion: pg_cron, dashboard, otra edge function, etc.';

alter table public.task_automation_runs enable row level security;

grant select on public.task_automation_runs to authenticated;

drop policy if exists "task_automation_runs_read_authenticated"
on public.task_automation_runs;

create policy "task_automation_runs_read_authenticated"
on public.task_automation_runs
for select
to authenticated
using (true);

create or replace function public.register_task_automation_run(
  p_run_type text default 'manual',
  p_source text default 'sql-function',
  p_notes text default null
)
returns public.task_automation_runs
language plpgsql
security definer
set search_path = public
as $$
declare
  v_total_tasks bigint;
  v_pending_tasks bigint;
  v_completed_tasks bigint;
  v_inserted_run public.task_automation_runs;
begin
  select
    count(*),
    count(*) filter (where not is_done),
    count(*) filter (where is_done)
  into v_total_tasks, v_pending_tasks, v_completed_tasks
  from public.tasks;

  insert into public.task_automation_runs (
    run_type,
    source,
    total_tasks,
    pending_tasks,
    completed_tasks,
    notes
  )
  values (
    coalesce(nullif(p_run_type, ''), 'manual'),
    coalesce(nullif(p_source, ''), 'sql-function'),
    v_total_tasks,
    v_pending_tasks,
    v_completed_tasks,
    nullif(p_notes, '')
  )
  returning * into v_inserted_run;

  return v_inserted_run;
end;
$$;

comment on function public.register_task_automation_run(text, text, text) is
  'Calcula totales de tareas y registra una ejecucion automatica para la charla 2';

revoke all on function public.register_task_automation_run(text, text, text)
from public, anon, authenticated;

grant execute on function public.register_task_automation_run(text, text, text)
to service_role;

-- Realtime opcional para observar nuevas ejecuciones desde clientes autenticados.
do $$
begin
  alter publication supabase_realtime add table public.task_automation_runs;
exception
  when duplicate_object then null;
end $$;

commit;
